<a href="https://colab.research.google.com/github/AnjaliJ4/Data-wrangling-2/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('/content/business-employment-data-march-2024-quarter.zip')
data

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22958,BDCQ.SEE3999A,2017.06,NaN,Y,C,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
22959,BDCQ.SEE3999A,2017.09,NaN,Y,C,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
22960,BDCQ.SEE3999A,2017.12,NaN,Y,C,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
22961,BDCQ.SEE3999A,2018.03,NaN,Y,C,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
22962,BDCQ.SEE3999A,2018.06,NaN,Y,C,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN